config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'
  
  namespace :api, defaults: { format: :json } do
    resources :users, except: [:create, :new, :edit] do
      resources :user_food_items, only: [:new, :destroy, :index, :show]
      resources :friendships, only: [:index]
    end
    resources :user_food_items, only: [:create, :destroy]
    resources :food_items, only: [:create, :search_food, :index, :show]
    resources :friendships, only: [:create, :destroy]
    resources :leaderboards, only: [:index]
    resources :comments, only: [:index, :create, :destroy]
  end
  
  resources :users, only: [:new, :create]
  resource :session, only: [:create, :new, :destroy]
  
  get '/food_items/search_food', to: 'api/food_items#search_food'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  include Commentable
  attr_reader :password
  
  validates :username, :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  before_validation :ensure_session_token
  
  has_many :user_food_items
  has_many :food_items, through: :user_food_items, source: :food_item
  
  has_many :friendships
  has_many :friends, through: :friendships, source: :friend
  
  has_many :authored_comments, class_name: "Comment", foreign_key: :author_id
  
  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user.try(:is_password?, password) ? user : nil
  end
  
  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end
  
  def email_hash
    Digest::MD5.hexdigest(self.email.downcase)
  end
  
  def password=(plain_text)
    if plain_text.present?
      @password = plain_text
      self.password_digest = BCrypt::Password.create(plain_text)
    end
  end
  
  def is_password?(plain_text)
    BCrypt::Password.new(self.password_digest).is_password?(plain_text)
  end
  
  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end
  
  def daily_user_food_items
    user_food_items = self.user_food_items
      .where(created_at: (DateTime.now.at_beginning_of_day.utc..Time.now.utc))
  end
  
  def daily_calories
    daily_cals = 0
    user_food_items = self.user_food_items
      .where(created_at: (DateTime.now.at_beginning_of_day.utc..Time.now.utc))
    
    user_food_items.each do |user_food_item|
      daily_cals += user_food_item.food_item.calories
    end
    
    daily_cals
  end
  
  def daily_nutrients
    nutrients = ["sodium", "dietary_fiber", "saturated_fat", "cholesterol",
      "vitamin_a", "vitamin_c", "calcium", "iron"]
    daily_nutrients = Hash.new(0)
    user_food_items = self.user_food_items
      .where(created_at: (DateTime.now.at_beginning_of_day.utc..Time.now.utc))
    
    user_food_items.each do |user_food_item|
      nutrients.each do |nutrient|
        if user_food_item.food_item.try(nutrient) == nil
          next
        else
          daily_nutrients[nutrient] += user_food_item.food_item.try(nutrient).floor
        end
      end
    end
    
    daily_nutrients
  end
  
  def weekly_calories
    weekly_cals = 0
    user_food_items = self.user_food_items
      .where(created_at: (7.days.ago...Time.now.utc))
      
    user_food_items.each do |user_food_item|
      weekly_cals += user_food_item.food_item.calories
    end
    
    weekly_cals
  end
  
  private
  
    def ensure_session_token
      self.session_token || self.class.generate_session_token
    end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApiController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    render partial: "api/users/user", locals: { user: @user}
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def index
    @users = User.all
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      login(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new, status: 422
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create User") %>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">

      <form action="<%= action %>" method="post">
        <input
           name="_method"
           type="hidden"
           value="<%= method %>">
        <input
           name="authenticity_token"
           type="hidden"
           value="<%= form_authenticity_token %>">

        <div class="form-group">
        <label for="user_username">Username</label>
        <input
           class="form-control input-group-lg"
           placeholder="Username"
           id="user_username"
           name="user[username]"
           type="text">
        </div>
				
        <div class="form-group">
        <label for="user_email">Email</label>
        <input
           class="form-control input-group-lg"
           placeholder="Email"
           id="user_username"
           name="user[email]"
           type="text">
        </div>

        <div class="form-group">
          <label for="user_password">Password</label>
          <input
             class="form-control"
             id="user_password"
             name="user[password]"
             type="password">
        </div>


        <button type="submit" class="btn btn-primary"><%= message %></button>
      </form>

  </div>
</div>

app/views/users/new.html.erb
<body class="sign-up">
	<div class="row">
	  <div class="col-xs-6 col-xs-offset-3">
		  <h1>Create User</h1>
	  </div>
  </div>
<%= render "form", :user => @user %>
</body>

app/views/users/show.html.erb
<div id="user-info">
	<h1><%= current_user.username %> Home</h1>
</div>
<div class="food-diary">
</div>