config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'
  
  namespace :api, defaults: { format: :json } do
    resources :users, except: [:create, :new, :edit] do
      resources :user_food_items, only: [:new, :destroy, :index, :show]
      resources :friendships, only: [:index]
    end
    resources :user_food_items, only: [:create, :destroy]
    resources :food_items, only: [:create, :search_food, :index, :show]
    resources :friendships, only: [:create, :destroy]
    resources :leaderboards, only: [:index]
    resources :comments, only: [:index, :create, :destroy]
  end
  
  resources :users, only: [:new, :create]
  resource :session, only: [:create, :new, :destroy]
  
  get '/food_items/search_food', to: 'api/food_items#search_food'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EatFriends</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
	<%= favicon_link_tag 'icon.png' %>
</head>
<body>
	
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
				<div class="header-icon">
				  <%= image_tag("icon.png") %>
				</div>
        <a class="navbar-brand">Eat With Friends</a>
			</div>

      <% if logged_in? %>
			
			<ul class="nav navbar-nav nav-pills">
				<li><a href="#">My Home</a></li>
				<li><a href="#/food_items/index">Search Foods</a></li>
				<li><a href="#/users/index">Find Friends</a></li>
				<li><a href="#/users/leaderboard">Leaderboard</a></li>
			</ul>
			
        <div class="dropdown pull-right navbar-form">
          <button type="button" class="btn btn-primary dropdown-toggle user-drop-down" data-toggle="dropdown">
            <%= current_user.username %>
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "Sign Out", session_url,
                     :method => :delete%></li>
          </ul>
        </div>
      <% else %>
        <div>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign In", new_session_url %></li>
            <li><%= link_to "Sign up", new_user_url %></li>
          </ul>
        </div>
      <% end %>
      </div>
  </nav>	
	
<%= render 'shared/errors' %>

<%= yield %>

  <!-- <nav class="navbar navbar-default navbar-bottom">
    <div class="footer-container">
      <p class="navbar-text pull-left">© 2014 - Site Built By George Groh
           <a href="http://tinyurl.com/tbvalid" target="_blank" >HTML 5 Validation</a>
      </p>
      
      <a href="http://youtu.be/zJahlKPCL9g" class="navbar-btn btn-danger btn pull-right">
       Eject</a>
    </div> 
	</nav> -->
	
</body>
</html>